// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: domain/flow/v1/flow.proto

package flowv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Payment lifecycle flow (single flow; SCA step is optional).
type PaymentFlow int32

const (
	PaymentFlow_PAYMENT_FLOW_UNSPECIFIED PaymentFlow = 0
	// Intent created, processing not finished.
	PaymentFlow_PAYMENT_FLOW_CREATED PaymentFlow = 1
	// Customer action required (3DS/SCA). This step is optional.
	PaymentFlow_PAYMENT_FLOW_WAITING_FOR_CONFIRMATION PaymentFlow = 2
	// Funds reserved (authorization hold).
	PaymentFlow_PAYMENT_FLOW_AUTHORIZED PaymentFlow = 3
	// Funds captured; payment completed.
	PaymentFlow_PAYMENT_FLOW_PAID PaymentFlow = 4
	// Payment refunded (full or partial).
	PaymentFlow_PAYMENT_FLOW_REFUNDED PaymentFlow = 5
	// Canceled by user/system (including void of authorization).
	PaymentFlow_PAYMENT_FLOW_CANCELED PaymentFlow = 6
	// Error/declined (including reverse/expire of authorization).
	PaymentFlow_PAYMENT_FLOW_FAILED PaymentFlow = 7
)

// Enum value maps for PaymentFlow.
var (
	PaymentFlow_name = map[int32]string{
		0: "PAYMENT_FLOW_UNSPECIFIED",
		1: "PAYMENT_FLOW_CREATED",
		2: "PAYMENT_FLOW_WAITING_FOR_CONFIRMATION",
		3: "PAYMENT_FLOW_AUTHORIZED",
		4: "PAYMENT_FLOW_PAID",
		5: "PAYMENT_FLOW_REFUNDED",
		6: "PAYMENT_FLOW_CANCELED",
		7: "PAYMENT_FLOW_FAILED",
	}
	PaymentFlow_value = map[string]int32{
		"PAYMENT_FLOW_UNSPECIFIED":              0,
		"PAYMENT_FLOW_CREATED":                  1,
		"PAYMENT_FLOW_WAITING_FOR_CONFIRMATION": 2,
		"PAYMENT_FLOW_AUTHORIZED":               3,
		"PAYMENT_FLOW_PAID":                     4,
		"PAYMENT_FLOW_REFUNDED":                 5,
		"PAYMENT_FLOW_CANCELED":                 6,
		"PAYMENT_FLOW_FAILED":                   7,
	}
)

func (x PaymentFlow) Enum() *PaymentFlow {
	p := new(PaymentFlow)
	*p = x
	return p
}

func (x PaymentFlow) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentFlow) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_flow_v1_flow_proto_enumTypes[0].Descriptor()
}

func (PaymentFlow) Type() protoreflect.EnumType {
	return &file_domain_flow_v1_flow_proto_enumTypes[0]
}

func (x PaymentFlow) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentFlow.Descriptor instead.
func (PaymentFlow) EnumDescriptor() ([]byte, []int) {
	return file_domain_flow_v1_flow_proto_rawDescGZIP(), []int{0}
}

var File_domain_flow_v1_flow_proto protoreflect.FileDescriptor

const file_domain_flow_v1_flow_proto_rawDesc = "" +
	"\n" +
	"\x19domain/flow/v1/flow.proto\x12\x0edomain.flow.v1*\xf3\x01\n" +
	"\vPaymentFlow\x12\x1c\n" +
	"\x18PAYMENT_FLOW_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PAYMENT_FLOW_CREATED\x10\x01\x12)\n" +
	"%PAYMENT_FLOW_WAITING_FOR_CONFIRMATION\x10\x02\x12\x1b\n" +
	"\x17PAYMENT_FLOW_AUTHORIZED\x10\x03\x12\x15\n" +
	"\x11PAYMENT_FLOW_PAID\x10\x04\x12\x19\n" +
	"\x15PAYMENT_FLOW_REFUNDED\x10\x05\x12\x19\n" +
	"\x15PAYMENT_FLOW_CANCELED\x10\x06\x12\x17\n" +
	"\x13PAYMENT_FLOW_FAILED\x10\aB\xc3\x01\n" +
	"\x12com.domain.flow.v1B\tFlowProtoP\x01ZHgithub.com/shortlink-org/billing/payments/internal/domain/flow/v1;flowv1\xa2\x02\x03DFX\xaa\x02\x0eDomain.Flow.V1\xca\x02\x0eDomain\\Flow\\V1\xe2\x02\x1aDomain\\Flow\\V1\\GPBMetadata\xea\x02\x10Domain::Flow::V1b\x06proto3"

var (
	file_domain_flow_v1_flow_proto_rawDescOnce sync.Once
	file_domain_flow_v1_flow_proto_rawDescData []byte
)

func file_domain_flow_v1_flow_proto_rawDescGZIP() []byte {
	file_domain_flow_v1_flow_proto_rawDescOnce.Do(func() {
		file_domain_flow_v1_flow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_flow_v1_flow_proto_rawDesc), len(file_domain_flow_v1_flow_proto_rawDesc)))
	})
	return file_domain_flow_v1_flow_proto_rawDescData
}

var file_domain_flow_v1_flow_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_domain_flow_v1_flow_proto_goTypes = []any{
	(PaymentFlow)(0), // 0: domain.flow.v1.PaymentFlow
}
var file_domain_flow_v1_flow_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_domain_flow_v1_flow_proto_init() }
func file_domain_flow_v1_flow_proto_init() {
	if File_domain_flow_v1_flow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_flow_v1_flow_proto_rawDesc), len(file_domain_flow_v1_flow_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_flow_v1_flow_proto_goTypes,
		DependencyIndexes: file_domain_flow_v1_flow_proto_depIdxs,
		EnumInfos:         file_domain_flow_v1_flow_proto_enumTypes,
	}.Build()
	File_domain_flow_v1_flow_proto = out.File
	file_domain_flow_v1_flow_proto_goTypes = nil
	file_domain_flow_v1_flow_proto_depIdxs = nil
}
