// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: adapter/tinkoff/proto/sandbox.proto

package investapi

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос открытия счета в песочнице.
type OpenSandboxAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"` // Название счета
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenSandboxAccountRequest) Reset() {
	*x = OpenSandboxAccountRequest{}
	mi := &file_adapter_tinkoff_proto_sandbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSandboxAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSandboxAccountRequest) ProtoMessage() {}

func (x *OpenSandboxAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adapter_tinkoff_proto_sandbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSandboxAccountRequest.ProtoReflect.Descriptor instead.
func (*OpenSandboxAccountRequest) Descriptor() ([]byte, []int) {
	return file_adapter_tinkoff_proto_sandbox_proto_rawDescGZIP(), []int{0}
}

func (x *OpenSandboxAccountRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// Номер открытого счета в песочнице.
type OpenSandboxAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"` //Номер счета
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenSandboxAccountResponse) Reset() {
	*x = OpenSandboxAccountResponse{}
	mi := &file_adapter_tinkoff_proto_sandbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSandboxAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSandboxAccountResponse) ProtoMessage() {}

func (x *OpenSandboxAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adapter_tinkoff_proto_sandbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSandboxAccountResponse.ProtoReflect.Descriptor instead.
func (*OpenSandboxAccountResponse) Descriptor() ([]byte, []int) {
	return file_adapter_tinkoff_proto_sandbox_proto_rawDescGZIP(), []int{1}
}

func (x *OpenSandboxAccountResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

// Запрос закрытия счета в песочнице.
type CloseSandboxAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"` //Номер счета
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSandboxAccountRequest) Reset() {
	*x = CloseSandboxAccountRequest{}
	mi := &file_adapter_tinkoff_proto_sandbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSandboxAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSandboxAccountRequest) ProtoMessage() {}

func (x *CloseSandboxAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adapter_tinkoff_proto_sandbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSandboxAccountRequest.ProtoReflect.Descriptor instead.
func (*CloseSandboxAccountRequest) Descriptor() ([]byte, []int) {
	return file_adapter_tinkoff_proto_sandbox_proto_rawDescGZIP(), []int{2}
}

func (x *CloseSandboxAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

// Результат закрытия счета в песочнице.
type CloseSandboxAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSandboxAccountResponse) Reset() {
	*x = CloseSandboxAccountResponse{}
	mi := &file_adapter_tinkoff_proto_sandbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSandboxAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSandboxAccountResponse) ProtoMessage() {}

func (x *CloseSandboxAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adapter_tinkoff_proto_sandbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSandboxAccountResponse.ProtoReflect.Descriptor instead.
func (*CloseSandboxAccountResponse) Descriptor() ([]byte, []int) {
	return file_adapter_tinkoff_proto_sandbox_proto_rawDescGZIP(), []int{3}
}

// Запрос пополнения счета в песочнице.
type SandboxPayInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"` //Номер счета
	Amount        *MoneyValue            `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`                        //Сумма пополнения счета в рублях
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxPayInRequest) Reset() {
	*x = SandboxPayInRequest{}
	mi := &file_adapter_tinkoff_proto_sandbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxPayInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxPayInRequest) ProtoMessage() {}

func (x *SandboxPayInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adapter_tinkoff_proto_sandbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxPayInRequest.ProtoReflect.Descriptor instead.
func (*SandboxPayInRequest) Descriptor() ([]byte, []int) {
	return file_adapter_tinkoff_proto_sandbox_proto_rawDescGZIP(), []int{4}
}

func (x *SandboxPayInRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *SandboxPayInRequest) GetAmount() *MoneyValue {
	if x != nil {
		return x.Amount
	}
	return nil
}

// Результат пополнения счета, текущий баланс.
type SandboxPayInResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       *MoneyValue            `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"` //Текущий баланс счета
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxPayInResponse) Reset() {
	*x = SandboxPayInResponse{}
	mi := &file_adapter_tinkoff_proto_sandbox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxPayInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxPayInResponse) ProtoMessage() {}

func (x *SandboxPayInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adapter_tinkoff_proto_sandbox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxPayInResponse.ProtoReflect.Descriptor instead.
func (*SandboxPayInResponse) Descriptor() ([]byte, []int) {
	return file_adapter_tinkoff_proto_sandbox_proto_rawDescGZIP(), []int{5}
}

func (x *SandboxPayInResponse) GetBalance() *MoneyValue {
	if x != nil {
		return x.Balance
	}
	return nil
}

var File_adapter_tinkoff_proto_sandbox_proto protoreflect.FileDescriptor

const file_adapter_tinkoff_proto_sandbox_proto_rawDesc = "" +
	"\n" +
	"#adapter/tinkoff/proto/sandbox.proto\x12%tinkoff.public.invest.api.contract.v1\x1a\"adapter/tinkoff/proto/common.proto\x1a\"adapter/tinkoff/proto/orders.proto\x1a&adapter/tinkoff/proto/operations.proto\x1a!adapter/tinkoff/proto/users.proto\x1a\x1fgoogle/api/field_behavior.proto\"=\n" +
	"\x19OpenSandboxAccountRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01B\a\n" +
	"\x05_name\";\n" +
	"\x1aOpenSandboxAccountResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"@\n" +
	"\x1aCloseSandboxAccountRequest\x12\"\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tB\x03\xe0A\x02R\taccountId\"\x1d\n" +
	"\x1bCloseSandboxAccountResponse\"\x89\x01\n" +
	"\x13SandboxPayInRequest\x12\"\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tB\x03\xe0A\x02R\taccountId\x12N\n" +
	"\x06amount\x18\x02 \x01(\v21.tinkoff.public.invest.api.contract.v1.MoneyValueB\x03\xe0A\x02R\x06amount\"c\n" +
	"\x14SandboxPayInResponse\x12K\n" +
	"\abalance\x18\x01 \x01(\v21.tinkoff.public.invest.api.contract.v1.MoneyValueR\abalance2\xa4\x12\n" +
	"\x0eSandboxService\x12\x99\x01\n" +
	"\x12OpenSandboxAccount\x12@.tinkoff.public.invest.api.contract.v1.OpenSandboxAccountRequest\x1aA.tinkoff.public.invest.api.contract.v1.OpenSandboxAccountResponse\x12\x8b\x01\n" +
	"\x12GetSandboxAccounts\x129.tinkoff.public.invest.api.contract.v1.GetAccountsRequest\x1a:.tinkoff.public.invest.api.contract.v1.GetAccountsResponse\x12\x9c\x01\n" +
	"\x13CloseSandboxAccount\x12A.tinkoff.public.invest.api.contract.v1.CloseSandboxAccountRequest\x1aB.tinkoff.public.invest.api.contract.v1.CloseSandboxAccountResponse\x12\x85\x01\n" +
	"\x10PostSandboxOrder\x127.tinkoff.public.invest.api.contract.v1.PostOrderRequest\x1a8.tinkoff.public.invest.api.contract.v1.PostOrderResponse\x12\x94\x01\n" +
	"\x15PostSandboxOrderAsync\x12<.tinkoff.public.invest.api.contract.v1.PostOrderAsyncRequest\x1a=.tinkoff.public.invest.api.contract.v1.PostOrderAsyncResponse\x12\x8b\x01\n" +
	"\x13ReplaceSandboxOrder\x12:.tinkoff.public.invest.api.contract.v1.ReplaceOrderRequest\x1a8.tinkoff.public.invest.api.contract.v1.PostOrderResponse\x12\x85\x01\n" +
	"\x10GetSandboxOrders\x127.tinkoff.public.invest.api.contract.v1.GetOrdersRequest\x1a8.tinkoff.public.invest.api.contract.v1.GetOrdersResponse\x12\x8b\x01\n" +
	"\x12CancelSandboxOrder\x129.tinkoff.public.invest.api.contract.v1.CancelOrderRequest\x1a:.tinkoff.public.invest.api.contract.v1.CancelOrderResponse\x12\x86\x01\n" +
	"\x14GetSandboxOrderState\x12;.tinkoff.public.invest.api.contract.v1.GetOrderStateRequest\x1a1.tinkoff.public.invest.api.contract.v1.OrderState\x12\x88\x01\n" +
	"\x13GetSandboxPositions\x127.tinkoff.public.invest.api.contract.v1.PositionsRequest\x1a8.tinkoff.public.invest.api.contract.v1.PositionsResponse\x12\x8b\x01\n" +
	"\x14GetSandboxOperations\x128.tinkoff.public.invest.api.contract.v1.OperationsRequest\x1a9.tinkoff.public.invest.api.contract.v1.OperationsResponse\x12\xa9\x01\n" +
	"\x1cGetSandboxOperationsByCursor\x12C.tinkoff.public.invest.api.contract.v1.GetOperationsByCursorRequest\x1aD.tinkoff.public.invest.api.contract.v1.GetOperationsByCursorResponse\x12\x88\x01\n" +
	"\x13GetSandboxPortfolio\x127.tinkoff.public.invest.api.contract.v1.PortfolioRequest\x1a8.tinkoff.public.invest.api.contract.v1.PortfolioResponse\x12\x87\x01\n" +
	"\fSandboxPayIn\x12:.tinkoff.public.invest.api.contract.v1.SandboxPayInRequest\x1a;.tinkoff.public.invest.api.contract.v1.SandboxPayInResponse\x12\x97\x01\n" +
	"\x18GetSandboxWithdrawLimits\x12<.tinkoff.public.invest.api.contract.v1.WithdrawLimitsRequest\x1a=.tinkoff.public.invest.api.contract.v1.WithdrawLimitsResponse\x12\x88\x01\n" +
	"\x11GetSandboxMaxLots\x128.tinkoff.public.invest.api.contract.v1.GetMaxLotsRequest\x1a9.tinkoff.public.invest.api.contract.v1.GetMaxLotsResponseB\x84\x02\n" +
	")com.tinkoff.public.invest.api.contract.v1B\fSandboxProtoP\x01Z\f./;investapi\xa2\x02\x05TPIAC\xaa\x02%Tinkoff.Public.Invest.Api.Contract.V1\xca\x02&Tinkoff\\Public_\\Invest\\Api\\Contract\\V1\xe2\x022Tinkoff\\Public_\\Invest\\Api\\Contract\\V1\\GPBMetadata\xea\x02*Tinkoff::Public::Invest::Api::Contract::V1b\x06proto3"

var (
	file_adapter_tinkoff_proto_sandbox_proto_rawDescOnce sync.Once
	file_adapter_tinkoff_proto_sandbox_proto_rawDescData []byte
)

func file_adapter_tinkoff_proto_sandbox_proto_rawDescGZIP() []byte {
	file_adapter_tinkoff_proto_sandbox_proto_rawDescOnce.Do(func() {
		file_adapter_tinkoff_proto_sandbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_adapter_tinkoff_proto_sandbox_proto_rawDesc), len(file_adapter_tinkoff_proto_sandbox_proto_rawDesc)))
	})
	return file_adapter_tinkoff_proto_sandbox_proto_rawDescData
}

var file_adapter_tinkoff_proto_sandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_adapter_tinkoff_proto_sandbox_proto_goTypes = []any{
	(*OpenSandboxAccountRequest)(nil),     // 0: tinkoff.public.invest.api.contract.v1.OpenSandboxAccountRequest
	(*OpenSandboxAccountResponse)(nil),    // 1: tinkoff.public.invest.api.contract.v1.OpenSandboxAccountResponse
	(*CloseSandboxAccountRequest)(nil),    // 2: tinkoff.public.invest.api.contract.v1.CloseSandboxAccountRequest
	(*CloseSandboxAccountResponse)(nil),   // 3: tinkoff.public.invest.api.contract.v1.CloseSandboxAccountResponse
	(*SandboxPayInRequest)(nil),           // 4: tinkoff.public.invest.api.contract.v1.SandboxPayInRequest
	(*SandboxPayInResponse)(nil),          // 5: tinkoff.public.invest.api.contract.v1.SandboxPayInResponse
	(*MoneyValue)(nil),                    // 6: tinkoff.public.invest.api.contract.v1.MoneyValue
	(*GetAccountsRequest)(nil),            // 7: tinkoff.public.invest.api.contract.v1.GetAccountsRequest
	(*PostOrderRequest)(nil),              // 8: tinkoff.public.invest.api.contract.v1.PostOrderRequest
	(*PostOrderAsyncRequest)(nil),         // 9: tinkoff.public.invest.api.contract.v1.PostOrderAsyncRequest
	(*ReplaceOrderRequest)(nil),           // 10: tinkoff.public.invest.api.contract.v1.ReplaceOrderRequest
	(*GetOrdersRequest)(nil),              // 11: tinkoff.public.invest.api.contract.v1.GetOrdersRequest
	(*CancelOrderRequest)(nil),            // 12: tinkoff.public.invest.api.contract.v1.CancelOrderRequest
	(*GetOrderStateRequest)(nil),          // 13: tinkoff.public.invest.api.contract.v1.GetOrderStateRequest
	(*PositionsRequest)(nil),              // 14: tinkoff.public.invest.api.contract.v1.PositionsRequest
	(*OperationsRequest)(nil),             // 15: tinkoff.public.invest.api.contract.v1.OperationsRequest
	(*GetOperationsByCursorRequest)(nil),  // 16: tinkoff.public.invest.api.contract.v1.GetOperationsByCursorRequest
	(*PortfolioRequest)(nil),              // 17: tinkoff.public.invest.api.contract.v1.PortfolioRequest
	(*WithdrawLimitsRequest)(nil),         // 18: tinkoff.public.invest.api.contract.v1.WithdrawLimitsRequest
	(*GetMaxLotsRequest)(nil),             // 19: tinkoff.public.invest.api.contract.v1.GetMaxLotsRequest
	(*GetAccountsResponse)(nil),           // 20: tinkoff.public.invest.api.contract.v1.GetAccountsResponse
	(*PostOrderResponse)(nil),             // 21: tinkoff.public.invest.api.contract.v1.PostOrderResponse
	(*PostOrderAsyncResponse)(nil),        // 22: tinkoff.public.invest.api.contract.v1.PostOrderAsyncResponse
	(*GetOrdersResponse)(nil),             // 23: tinkoff.public.invest.api.contract.v1.GetOrdersResponse
	(*CancelOrderResponse)(nil),           // 24: tinkoff.public.invest.api.contract.v1.CancelOrderResponse
	(*OrderState)(nil),                    // 25: tinkoff.public.invest.api.contract.v1.OrderState
	(*PositionsResponse)(nil),             // 26: tinkoff.public.invest.api.contract.v1.PositionsResponse
	(*OperationsResponse)(nil),            // 27: tinkoff.public.invest.api.contract.v1.OperationsResponse
	(*GetOperationsByCursorResponse)(nil), // 28: tinkoff.public.invest.api.contract.v1.GetOperationsByCursorResponse
	(*PortfolioResponse)(nil),             // 29: tinkoff.public.invest.api.contract.v1.PortfolioResponse
	(*WithdrawLimitsResponse)(nil),        // 30: tinkoff.public.invest.api.contract.v1.WithdrawLimitsResponse
	(*GetMaxLotsResponse)(nil),            // 31: tinkoff.public.invest.api.contract.v1.GetMaxLotsResponse
}
var file_adapter_tinkoff_proto_sandbox_proto_depIdxs = []int32{
	6,  // 0: tinkoff.public.invest.api.contract.v1.SandboxPayInRequest.amount:type_name -> tinkoff.public.invest.api.contract.v1.MoneyValue
	6,  // 1: tinkoff.public.invest.api.contract.v1.SandboxPayInResponse.balance:type_name -> tinkoff.public.invest.api.contract.v1.MoneyValue
	0,  // 2: tinkoff.public.invest.api.contract.v1.SandboxService.OpenSandboxAccount:input_type -> tinkoff.public.invest.api.contract.v1.OpenSandboxAccountRequest
	7,  // 3: tinkoff.public.invest.api.contract.v1.SandboxService.GetSandboxAccounts:input_type -> tinkoff.public.invest.api.contract.v1.GetAccountsRequest
	2,  // 4: tinkoff.public.invest.api.contract.v1.SandboxService.CloseSandboxAccount:input_type -> tinkoff.public.invest.api.contract.v1.CloseSandboxAccountRequest
	8,  // 5: tinkoff.public.invest.api.contract.v1.SandboxService.PostSandboxOrder:input_type -> tinkoff.public.invest.api.contract.v1.PostOrderRequest
	9,  // 6: tinkoff.public.invest.api.contract.v1.SandboxService.PostSandboxOrderAsync:input_type -> tinkoff.public.invest.api.contract.v1.PostOrderAsyncRequest
	10, // 7: tinkoff.public.invest.api.contract.v1.SandboxService.ReplaceSandboxOrder:input_type -> tinkoff.public.invest.api.contract.v1.ReplaceOrderRequest
	11, // 8: tinkoff.public.invest.api.contract.v1.SandboxService.GetSandboxOrders:input_type -> tinkoff.public.invest.api.contract.v1.GetOrdersRequest
	12, // 9: tinkoff.public.invest.api.contract.v1.SandboxService.CancelSandboxOrder:input_type -> tinkoff.public.invest.api.contract.v1.CancelOrderRequest
	13, // 10: tinkoff.public.invest.api.contract.v1.SandboxService.GetSandboxOrderState:input_type -> tinkoff.public.invest.api.contract.v1.GetOrderStateRequest
	14, // 11: tinkoff.public.invest.api.contract.v1.SandboxService.GetSandboxPositions:input_type -> tinkoff.public.invest.api.contract.v1.PositionsRequest
	15, // 12: tinkoff.public.invest.api.contract.v1.SandboxService.GetSandboxOperations:input_type -> tinkoff.public.invest.api.contract.v1.OperationsRequest
	16, // 13: tinkoff.public.invest.api.contract.v1.SandboxService.GetSandboxOperationsByCursor:input_type -> tinkoff.public.invest.api.contract.v1.GetOperationsByCursorRequest
	17, // 14: tinkoff.public.invest.api.contract.v1.SandboxService.GetSandboxPortfolio:input_type -> tinkoff.public.invest.api.contract.v1.PortfolioRequest
	4,  // 15: tinkoff.public.invest.api.contract.v1.SandboxService.SandboxPayIn:input_type -> tinkoff.public.invest.api.contract.v1.SandboxPayInRequest
	18, // 16: tinkoff.public.invest.api.contract.v1.SandboxService.GetSandboxWithdrawLimits:input_type -> tinkoff.public.invest.api.contract.v1.WithdrawLimitsRequest
	19, // 17: tinkoff.public.invest.api.contract.v1.SandboxService.GetSandboxMaxLots:input_type -> tinkoff.public.invest.api.contract.v1.GetMaxLotsRequest
	1,  // 18: tinkoff.public.invest.api.contract.v1.SandboxService.OpenSandboxAccount:output_type -> tinkoff.public.invest.api.contract.v1.OpenSandboxAccountResponse
	20, // 19: tinkoff.public.invest.api.contract.v1.SandboxService.GetSandboxAccounts:output_type -> tinkoff.public.invest.api.contract.v1.GetAccountsResponse
	3,  // 20: tinkoff.public.invest.api.contract.v1.SandboxService.CloseSandboxAccount:output_type -> tinkoff.public.invest.api.contract.v1.CloseSandboxAccountResponse
	21, // 21: tinkoff.public.invest.api.contract.v1.SandboxService.PostSandboxOrder:output_type -> tinkoff.public.invest.api.contract.v1.PostOrderResponse
	22, // 22: tinkoff.public.invest.api.contract.v1.SandboxService.PostSandboxOrderAsync:output_type -> tinkoff.public.invest.api.contract.v1.PostOrderAsyncResponse
	21, // 23: tinkoff.public.invest.api.contract.v1.SandboxService.ReplaceSandboxOrder:output_type -> tinkoff.public.invest.api.contract.v1.PostOrderResponse
	23, // 24: tinkoff.public.invest.api.contract.v1.SandboxService.GetSandboxOrders:output_type -> tinkoff.public.invest.api.contract.v1.GetOrdersResponse
	24, // 25: tinkoff.public.invest.api.contract.v1.SandboxService.CancelSandboxOrder:output_type -> tinkoff.public.invest.api.contract.v1.CancelOrderResponse
	25, // 26: tinkoff.public.invest.api.contract.v1.SandboxService.GetSandboxOrderState:output_type -> tinkoff.public.invest.api.contract.v1.OrderState
	26, // 27: tinkoff.public.invest.api.contract.v1.SandboxService.GetSandboxPositions:output_type -> tinkoff.public.invest.api.contract.v1.PositionsResponse
	27, // 28: tinkoff.public.invest.api.contract.v1.SandboxService.GetSandboxOperations:output_type -> tinkoff.public.invest.api.contract.v1.OperationsResponse
	28, // 29: tinkoff.public.invest.api.contract.v1.SandboxService.GetSandboxOperationsByCursor:output_type -> tinkoff.public.invest.api.contract.v1.GetOperationsByCursorResponse
	29, // 30: tinkoff.public.invest.api.contract.v1.SandboxService.GetSandboxPortfolio:output_type -> tinkoff.public.invest.api.contract.v1.PortfolioResponse
	5,  // 31: tinkoff.public.invest.api.contract.v1.SandboxService.SandboxPayIn:output_type -> tinkoff.public.invest.api.contract.v1.SandboxPayInResponse
	30, // 32: tinkoff.public.invest.api.contract.v1.SandboxService.GetSandboxWithdrawLimits:output_type -> tinkoff.public.invest.api.contract.v1.WithdrawLimitsResponse
	31, // 33: tinkoff.public.invest.api.contract.v1.SandboxService.GetSandboxMaxLots:output_type -> tinkoff.public.invest.api.contract.v1.GetMaxLotsResponse
	18, // [18:34] is the sub-list for method output_type
	2,  // [2:18] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_adapter_tinkoff_proto_sandbox_proto_init() }
func file_adapter_tinkoff_proto_sandbox_proto_init() {
	if File_adapter_tinkoff_proto_sandbox_proto != nil {
		return
	}
	file_adapter_tinkoff_proto_common_proto_init()
	file_adapter_tinkoff_proto_orders_proto_init()
	file_adapter_tinkoff_proto_operations_proto_init()
	file_adapter_tinkoff_proto_users_proto_init()
	file_adapter_tinkoff_proto_sandbox_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_adapter_tinkoff_proto_sandbox_proto_rawDesc), len(file_adapter_tinkoff_proto_sandbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_adapter_tinkoff_proto_sandbox_proto_goTypes,
		DependencyIndexes: file_adapter_tinkoff_proto_sandbox_proto_depIdxs,
		MessageInfos:      file_adapter_tinkoff_proto_sandbox_proto_msgTypes,
	}.Build()
	File_adapter_tinkoff_proto_sandbox_proto = out.File
	file_adapter_tinkoff_proto_sandbox_proto_goTypes = nil
	file_adapter_tinkoff_proto_sandbox_proto_depIdxs = nil
}
