with-expecter: True
inpackage: True
dir: mocks
mockname: "{{.InterfaceName}}"
outpkg: "{{.PackageName}}mock"
filename: "{{.InterfaceName}}.go"
packages:
  github.com/shortlink-org/billing/billing/internal/infrastructure/repository/account:
    interfaces:
      Repository:
